spring.application.name=cramanager
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5435/cramanager
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
cramanager.secretkey=cdc4868646ae9aac42db2c933cb4f6838e518a532d531cf60e474cbe016b9539